// <auto-generated />
using System;
using CityWebsiteAuditDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityWebsiteAuditDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715173634_AddWaveAccessibilityIssues")]
    partial class AddWaveAccessibilityIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CityWebsiteAuditDashboard.Models.WaveAccessibilityIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("IssueCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WebsiteScanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteScanId");

                    b.ToTable("WaveAccessibilityIssues");
                });

            modelBuilder.Entity("CityWebsiteAuditDashboard.Models.WebsiteScan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateScanned")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("IPv4Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ResponseTimeMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ScanError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WaveAlerts")
                        .HasColumnType("int");

                    b.Property<int?>("WaveAria")
                        .HasColumnType("int");

                    b.Property<int?>("WaveContrastErrors")
                        .HasColumnType("int");

                    b.Property<string>("WaveErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WaveErrors")
                        .HasColumnType("int");

                    b.Property<int?>("WaveFeatures")
                        .HasColumnType("int");

                    b.Property<bool?>("WaveScanSucceeded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("WaveScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("XPoweredByHeader")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebsiteScans");
                });

            modelBuilder.Entity("CityWebsiteAuditDashboard.Models.WaveAccessibilityIssue", b =>
                {
                    b.HasOne("CityWebsiteAuditDashboard.Models.WebsiteScan", "WebsiteScan")
                        .WithMany("WaveAccessibilityIssues")
                        .HasForeignKey("WebsiteScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebsiteScan");
                });

            modelBuilder.Entity("CityWebsiteAuditDashboard.Models.WebsiteScan", b =>
                {
                    b.Navigation("WaveAccessibilityIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
